Rails/CatSharingAuth/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end

  resources :users, only: [:create, :new]
  resource :session, only: [:create, :new, :destroy]

  root to: redirect('/cats')
end

Rails/CatSharingAuth/app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :session_token, presence: true, uniqueness: true
    validates :password, length: {minimum: 6, maximum: 16, allow_nil: true}

    before_validation :ensure_session_token

    attr_reader :password

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        return nil if user.nil?
        return user.is_password?(password) ? user : nil
    end

    def ensure_session_token
        self.session_token ||= self.class.generate_session_token
    end

    def reset_session_token!
        self.session_token = self.class.generate_session_token
        self.save
    end

    def self.generate_session_token
        SecureRandom::urlsafe_base64(16)
    end

    def password=(password)
        @password = password
        self.password_digest = self.class.encrypt_password(password)
    end

    def self.encrypt_password(password)
        BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end
end

Rails/CatSharingAuth/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def create
        user = User.new(user_params)
        if user.save
            log_in(user)
        else 
            flash.now[:errors] = user.errors.full_messages
            render :new
        end
    end

    def new
        render :new
    end
    
    private 
    def user_params
        params.require(:user).permit(:username, :password)
    end

end

Rails/CatSharingAuth/app/views/users/new.html.erb
<%= render 'shared/errors' %>

<form action="<%= users_url %>" method="post">
    <input
          type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="post">

    <label for="username">Username: </label>
    <input type="text" name="user[username]" id="username">

    <label for="password">Password: </label>
    <input type="text" name="user[password]" id="password">

    <input type="submit" value="Sign Up">
</form>